repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: ^tests/
  - repo: https://github.com/python-poetry/poetry
    rev: "1.6.1"
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        name: export requirements.txt
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
      - id: poetry-export
        name: export requirements-dev.txt
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements-dev.txt",
            "--only",
            "dev",
          ]
